#ifndef PARGEMSLR_CUDA_COMPAT_H
#define PARGEMSLR_CUDA_COMPAT_H

#ifdef PARGEMSLR_CUDA
#include "cusparse.h"

#ifndef PARGEMSLR_CUDA_VERSION
#define PARGEMSLR_CUDA_VERSION 10
#endif

#ifndef PARGEMSLR_CUSPARSE_GENERIC_API
#ifdef CUSPARSE_VERSION
#if (CUSPARSE_VERSION >= 11000)
#define PARGEMSLR_CUSPARSE_GENERIC_API 1
#else
#define PARGEMSLR_CUSPARSE_GENERIC_API 0
#endif
#elif (PARGEMSLR_CUDA_VERSION >= 11)
#define PARGEMSLR_CUSPARSE_GENERIC_API 1
#else
#define PARGEMSLR_CUSPARSE_GENERIC_API 0
#endif
#endif

#else
#ifndef PARGEMSLR_CUSPARSE_GENERIC_API
#define PARGEMSLR_CUSPARSE_GENERIC_API 0
#endif
#endif

#endif
